runtime: nodejs16
handlers:
  # Serve all static files with urls ending with a file extension
- url: /(.*\..+)$ 
  static_files: switch-career/dist/\1
  upload: switch-career/dist/(.*\..+)$
  # catch all handler to index.html
- url: /.*
  static_files: switch-career/dist/index.html
  upload: switch-career/dist/index.html